config/routes.rb
Rails.application.routes.draw do

  devise_for :accounts, :controllers =>{:registrations => 'accounts/registrations',:confirmations => 'accounts/confirmations'}
  post "likes/:post_id/create" => "likes#create"
  post "likes/:post_id/destroy" => "likes#destroy"



  get "admin/user" => "admin#user"
  post "admin/user" => "admin#user"
  post "admin/user/:user_id/ban" =>"admin#user_ban"
  post "admin/user/:user_id/suspend" =>"admin#user_suspend"
  get 'admin/post' => "admin#post"
  post 'admin/post' => "admin#post"
  get 'admin/transaction'

  post "users/:id/update"  => "users#update"
  get "users/edit"     => "users#edit"
  post "users/edit_confirm" => "users#edit_confirm"
  post "users/update"      => "users#update"
  post "users/create"      => "users#create"
  get "users/index"        => "users#index"
  get "users/show/:id"          => "users#show"
  post "login"             => "home#login"
  post "logout"            => "home#logout"
  get "login"              => "home#login"
  get "users/mail_confirm"       => "users#mail_confirm", as: 'users_mail_confirm'
  get "users/signup"             => "users#signup", as: 'users_signup'
  get "users/signup_confirm"     => "users#signup_confirm"
  post "users/signup_confirm"    => "users#signup_confirm"


  get "posts/search" => "posts#search"
  post "posts/search" => "posts#search"
  get "posts/index" => "posts#index"
  get "posts/new" => "posts#new"
  get "posts/show/:id" => "posts#show"
  post "posts/create" => "posts#create"
  post "posts/create_confirm" => "posts#create_confirm"
  get "posts/edit/:id" => "posts#edit"
  post "posts/edit_confirm/:id" => "posts#edit_confirm"
  post "posts/update/:id" => "posts#update"
  post "posts/destroy/:id" => "posts#destroy"
  get "posts/chat_confirm/:id" => "posts#chat_confirm"

  post "chats/:book_id/start"            => "chats#start"
  post "chats/:transaction_id/send_chat" => "chats#send_chat"
  get "chats/:transaction_id/chat"       => "chats#chat"
  post "chats/:transaction_id/cansel_exhibit"  => "chats#cansel_exhibit"
  post "chats/:transaction_id/cansel_parchase" => "chats#cansel_parchase"
  get "chats/:transaction_id/buy_complete_comfirm"        => "chats#buy_complete_comfirm"
  post "chats/:transaction_id/buy_complete_comfirm_done"  => "chats#buy_complete_comfirm_done"
  get "chats/:transaction_id/sale_complete_comfirm"       => "chats#sale_complete_comfirm"
  post "chats/:transaction_id/sale_complete_comfirm_done" => "chats#sale_complete_comfirm_done"




  root 'home#top'
  get 'home/top' => 'home#top'
  get "/about" => 'home#about'
  get "/policy" => 'home#policy'
  get "/privacy" => 'home#privacy'
  get "/help" => 'home#help'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'index/index'
  # post "index/index"
  #
  # get 'index', to: 'index#index'
  # get 'index/chatani'
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :account
  belongs_to :course
  has_many :posts
  has_many :parchase_transactions, class_name: 'Transaction', :foreign_key => 'parchase_user_id'
  has_many :exhibit_transactions, class_name: 'Transaction', :foreign_key => 'exhibit_user_id'
  # 投稿とのアソシエーション

  mount_uploader :icon, PictureUploader

  #VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  #validates :email, presence: true, uniqueness: true, length: { maximum: 255 }, format: {with: VALID_EMAIL_REGEX}
  #validates :password, presence: true, length: {minimum: 6}
  validates :name, presence: true,length: { maximum: 50 }

  enum gender: { man: 0, woman: 1, other: 2}

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Common

  before_action :authenticate_account!, except: [:mail_confirm]
  before_action :check_current_user, except: [:signup, :signup_confirm, :mail_confirm, :create]


  def show
    @user = User.find_by(id: params[:id])
    @user_great = entry_year_to_great(@user.entry_year)

    #取引一覧表示用
    @parchase_transactions = Transaction
    .where(parchase_user_id: @current_user.id)
    .where(parchase_status: Transaction.parchase_statuses[:parchase_normal])
    @exhibit_transactions = Transaction
    .where(exhibit_user_id: @current_user.id)
    .where(exhibit_status: Transaction.exhibit_statuses[:exhibit_normal])

    #自取引一覧
    @posts = Post.where("user_id = ?", @current_user.id)
  end

  def new
    @user = User.new
  end

  def signup
    @user = User.new
    today = get_today()
    @entry_year = today.year
    @course_id = 1001
    @select_entry_year = get_select_entry_year()
  end

  def signup_confirm
    @user = User.new
    @user.name = params[:name]
    @user.course_id = params[:course_id].to_i
    @user.entry_year = params[:entry_year].to_i
    @user_great = entry_year_to_great(@user.entry_year)
    @user.club = params[:club]
    @user.gender = params[:gender].to_i
    if params[:icon] then
      @user.icon = params[:icon]
      @user.icon.cache!
    end
    @user.account_id = @current_account_id

    @select_entry_year = get_select_entry_year()

    if !@user.valid? then
      flash[:notice] = @user.errors.full_messages
      render("users/signup")
    end

  end

  #新規登録実行
  def create
    @user = User.new
    @user.name = params[:name]
    @user.course_id = params[:course_id].to_i
    @user.entry_year = params[:entry_year].to_i
    @user.club = params[:club]
    @user.gender = params[:gender].to_i
    if params[:cache].present? && params[:cache][:icon].present? then
      @user.icon.retrieve_from_cache! params[:cache][:icon]
    end

    if params[:back] then
      @select_entry_year = get_select_entry_year()
      render("users/signup")
      return
    end

    @user.account_id = @current_account_id

    if !@user.save then
      flash[:notice] = @user.errors.full_messages
      render("users/signup")
      return
    end

    flash[:notice] = "ユーザー登録が完了しました"
    redirect_to("/")


  # @user = User.new(
  #   account_id: @current_account_id,
  #   name: params[:name],
  #   gender: params[:gender_type].to_i,
  #   image_name: "default_user.jpg",
  # )
  # if @user.save
  #   session[:user_id] = @user.id
  #   flash[:notice] = "ユーザー登録が完了しました"
  #   redirect_to("/users/#{@user.id}")
  # else
  #   flash[:notice] = @user.errors.full_messages
  #   render("users/signup")
  # end
  end

  #[1]編集画面
  def edit
    @user = User.find_by(id: @current_user.id)
    @select_course = get_select_course()
    @select_entry_year = get_select_entry_year()
  end

  #[2]更新確認
  def edit_confirm
    @user = User.new
    @user.name = params[:name]
    @user.course_id = params[:course_id].to_i
    @user.entry_year = params[:entry_year].to_i
    @user_great = entry_year_to_great(@user.entry_year)
    @user.club = params[:club]
    @user.gender = params[:gender].to_i
    if params[:icon] then
      @user.icon = params[:icon]
      @user.icon.cache!
    end

    user_course = Course.find_by(course_id: @user.course_id)
    @course_name = user_course.name

    @select_course = get_select_course()
    @select_entry_year = get_select_entry_year()

    if !@user.valid? then
      flash[:notice] = @user.errors.full_messages
      render("users/edit")
    end

  end

  #[3]更新登録実行
  def update
    @user = User.find_by(id: @current_user.id)
    @user.name = params[:name]
    @user.course_id = params[:course_id].to_i
    @user.entry_year = params[:entry_year].to_i
    @user.club = params[:club]
    @user.gender = params[:gender].to_i
    if params[:cache].present? && params[:cache][:icon].present? then
      @user.icon.retrieve_from_cache! params[:cache][:icon]
    end

    #戻るボタン
    if params[:back] then #[1]へ
      @select_course = get_select_course()
      @select_entry_year = get_select_entry_year()
      render("users/edit")
      return
    end

    @user.account_id = @current_account_id

    if !@user.save then
      flash[:notice] = @user.errors.full_messages
      render("users/edit")
      return
    end

    flash[:notice] = "ユーザー登録が完了しました"
    redirect_to("/users/show/#{@current_user.id}")
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="wrapper">
    <main class="container">
  		<div class="contents"><!-- ここまで定型 -->
            <div class="cttHead"><!-- コンテンツの見出し -->
				<h2>ユーザー情報編集</h2>
		  	</div>
            <div class="mainForm"><!-- フォーム作るときはこれ　tagはdivがよさげ -->
                <%= form_tag("/users/edit_confirm",{:multipart => true}) do %>
                    <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
                        <label>ニックネーム</label>
                        <strong>必須</strong>
                        <%= text_field_tag("name", @user.name, {:class =>'form-element form-field'})%>
                    </div>

                    <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
                        <label>所属課程・専攻</label>
                        <%= select_tag("course_id",
                        options_for_select(@select_course,:selected => @user.course_id),
                        {class: "form-element form-select"})%>
                    </div>

                    <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
                        <label>サークル・部活動</label>
                        <%= text_field_tag("club",@user.club, {:class =>'form-element form-field'})%>
                    </div>

                    <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
                        <label>学年</label>
                        <strong>必須</strong><!-- 必須マーク -->
                        <%= select_tag("entry_year",
                        options_for_select(@select_entry_year,:selected => @user.entry_year),
                        {class: "form-element form-select"})%>
                    </div>

                    <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
                        <label>性別</label>
                        <strong>必須</strong><!-- 必須マーク -->
                        <%= select_tag("gender",
                        options_for_select(User.genders.map { |key, value| [I18n.t("enums.user.gender.#{key}"), value] }, :selected => User.genders[@user.gender]),
                        {class: "form-element form-select"})%>
                    </div>

                    <div class="form-element-wrapper">
                        <label>アイコン</label>
                        <div class="form-icon">
                            <%= image_tag @user.icon.to_s %>
                        </div>
                        <p>↑ 元のアイコン</p>
                    </div>
                    <div class="form-element-wrapper">
                        <div class="btn-file button button-Gray form-element">
                            ファイルを選択
                            <%= file_field_tag( 'icon', :class =>'button') %>
                        </div>
                    </div>

                     <%= submit_tag("確認画面へ", :class =>'form-element button button-Primary') %>
                <% end %>
            </div>
        </div>
    </main>


</div>

app/views/users/edit_confirm.html.erb
<%# <h1>ユーザ編集確認画面</h1> %>
<div class="wrapper">
  <main class="container">
  	<div class="contents"><!-- ここまで定型 -->
      <div class="cttHead"><!-- コンテンツの見出し -->
			  <h2>登録情報確認</h2>
	    </div>
      <div class="mainForm"><!-- フォーム作るときはこれ　tagはdivがよさげ -->
        <%= form_tag("/users/update",{:multipart => true}) do %>
          <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
            <label>ニックネーム</label>
            <%= @user.name %>
            <%= hidden_field_tag "name", @user.name, :class =>'form-element' %>
          </div>

          <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
            <label>所属課程・専攻</label>
            <%= @course_name %>
            <%= hidden_field_tag "course_id", @user.course_id, :class =>'form-element' %>
          </div>

          <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
            <label>サークル・部活動</label>
              <% if @user.club.present? then %>
                <%= @user.club %>
                <%= hidden_field_tag "club", @user.club, :class =>'form-element' %>
              <% else %>
                <p>選択されていません</p>
              <% end %>
          </div>

          <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
            <label>学年</label>
              <%= @user_great %>
              <%= hidden_field_tag "entry_year", @user.entry_year, :class =>'form-element' %>

          </div>

          <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
            <label>性別</label>
              <%= @user.gender_i18n %>
              <%= hidden_field_tag "gender", User.genders[@user.gender], :class =>'form-element' %>
          </div>

          <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
            <label>アイコン</label>
            <div class="form-icon">
              <% if @user.icon.url then %>
                <%= image_tag @user.icon.url %>
                <%= hidden_field_tag :"cache[icon]", @user.icon.cache_name, :class =>'form-element' %>
              <% end %>
            </div>
          </div>
          <%= submit_tag("登録", :class =>'form-element button button-Primary') %>
          <%= submit_tag("修正する",name: 'back', :class =>'form-element button button-Alert') %>

        <% end %>
      </div>
    </div>
  </main>
</div>

app/views/users/mail_confirm.html.erb
<div class="wrapper">
    <main class="container">
        <div class="contents">
            <h2>メール送信完了！</h2>
            <p>メールをご確認ください</p>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="wrapper">
    <main class="container">
        <div class="contents row">
            <div class="cttHead">
                <h2>あなたの会員情報</h2>
            </div>
            <div class="col-md-6">
                <div class="mainCard">
                    <div class="mainForm">
                        <div class="form-element-wrapper">
                            <div class="form-icon">
                                <% if @user.icon.url then %>
                                <%= image_tag @user.icon.url %>
                                <% end %>
                            </div>
                        </div>
                        <div class="form-element-wrapper nick">
                            <p><%= @user.name %></p>
                            <span>平均評価</span><span class="hyoka">3.4</span>
                            <span>出品取引数</span><span class="hyoka">1</span>
                            <span>購入取引数</span><span class="hyoka">1</span>
                        </div>
                        <div class="form-element-wrapper">
                            <label>所属課程・専攻</label>
                            <p><%= @course_name %></p>
                        </div>
                        <div class="form-element-wrapper">
                            <label>サークル・部活動</label>
                            <p>
                                <% if @user.club.present? then %>
                                <%= @user.club %>
                                <% else %>
                                選択されていません
                                <% end %>
                            </p>
                        </div>
                        <div class="form-element-wrapper">
                            <label>学年</label>
                            <p>
                                <%= @user_great %>
                            </p>
                        </div>
                        <div class="form-element-wrapper">
                            <label>性別</label>
                            <p>
                                <%= @user.gender_i18n %>
                            </p>
                        </div>
                        <% if @user.id == @current_user.id %>
                        <div class="form-element-wrapper">
                            <%= link_to("編集", "/users/edit", :class =>'form-element button button-Primary') %>
                        </div>
                        <% end %>

                        <div class="form-element-wrapper">
                            <%= link_to(account_registration_path(id: @current_user.id), method: :delete, :class =>'form-element button button-Alert') do %>
                            退会する
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="mainCard">
                    <div class="mainForm">
                        <h3>購入取引一覧</h3>
                        <div class="form-element-wrapper">
                            <% @parchase_transactions.each do |transaction| %>
                            <h4 class="panel-title accordion-toggle">
                                <button class="form-element button button-White" data-toggle="collapse" data-parent="#accordion" href="#<%= transaction.id %>">
                                    <%= transaction.exhibit_user.name %>さんとの取引
                                </button>
                            </h4>
                            <div id="<%= transaction.id %>" class="panel-collapse collapse">
                                <%= link_to("/chats/#{transaction.id}/chat", :class=>"form-element button button-Primary") do %>
                                "チャットを開始",
                                <%# 変更必要かも %>
                                <%end%>
                                <%= link_to("購入中止","/chats/#{transaction.id}/cansel_parchase",{method:"post", :class=>"form-element button button-Alert"}) %>
                            </div>
                            <% end %>
                        </div>
                        <h3>出品取引一覧</h3>
                        <div class="form-element-wrapper">
                            <% @exhibit_transactions.each do |transaction| %>
                            <div class="panel-title accordion-toggle">
                                <button class="form-element button button-White" data-toggle="collapse" data-parent="#accordion" href="#<%= transaction.id %>">
                                    <%= transaction.parchase_user.name %>さんとの取引
                                </button>
                            </div>
                            <div id="<%= transaction.id %>" class="panel-collapse collapse">
                                <%= link_to("チャットを開始","/chats/#{transaction.id}/chat", :class=>"form-element button button-Primary") %>
                                <%= link_to("出品中止","/chats/#{transaction.id}/cansel_exhibit",{method:"post", :class=>"form-element button button-Alert"}) %>
                            </div>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="mainCard">
                    <div class="mainForm">
                        <h3>出品物一覧</h3>
                        <div class="contents-itemCard">
                            <% @posts.each do |post| %>
                            <div class="itemCard">
                                <div class="itemCard-wrapper">
                                    <a href="/posts/show/<%= post.id %>">
                                        <figure class="item-img">
                                            <%= image_tag post.image_name1.url %>
                                        </figure>
                                    </a>
                                    <div class="item-body">
                                        <div class="item-name">
                                            <span><%= post.name %></span>
                                        </div>
                                        <div class="item-price">
                                            <span><%= post.price %>円</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>

app/views/users/signup.html.erb
<div class="wrapper">
    <main class="container">
  		<div class="contents"><!-- ここまで定型 -->
            <div class="cttHead"><!-- コンテンツの見出し -->
				<h2>ユーザー情報登録</h2>
		  	</div>
            <div class="mainForm"><!-- フォーム作るときはこれ　tagはdivがよさげ -->
                <%= form_tag("/users/signup_confirm",{:multipart => true}) do %>
                    <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
                        <label>ニックネーム</label>
                        <strong>必須</strong><!-- 必須マーク -->
                        <%= text_field_tag("name",@user.name, :class =>'form-element form-field')%>
                    </div>

                    <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
                        <label>所属課程・専攻</label>
                        <%= select_tag("course_id",
                        options_for_select(Course.all.map {|v| [v.name, v.id]},:selected => @user.id),
                        {class: "form-element"})%>
                    </div>

                    <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
                        <label>サークル・部活動</label>
                        <%= text_field_tag("club",@user.club, :class =>'form-element form-field')%>
                    </div>

                    <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
                        <label>学年</label>
                        <strong>必須</strong><!-- 必須マーク -->
                        <%= select_tag("entry_year",
                        options_for_select(@select_entry_year,:selected => @user.entry_year),
                        {class: "form-element"})%>
                    </div>

                    <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
                        <label>性別</label>
                        <strong>必須</strong><!-- 必須マーク -->
                        <%= select_tag("gender",
                        options_for_select(User.genders.map { |key, value| [I18n.t("enums.user.gender.#{key}"), value] }, :selected => User.genders[@user.gender]),
                        {class: "form-element"})%>
                    </div>

                    <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
                        <label>アイコン</label>
                        <%= file_field_tag( 'icon', :class =>'form-element') %>
                    </div>

         <%= submit_tag("確認画面へ", :class =>'form-element button button-Primary') %>
<% end %>
            </div>
        </div>
    </main>

</div>

app/views/users/signup2.html.erb
<h2>メール送信完了！</h2>
<p>メールをご確認ください</p>

app/views/users/signup3.html.erb
<div class="wrapper">
	<header class="slimHead"><!-- ボタン無しヘッダー -->
        <div class="logo">
			<a href="#"><img src="#" alt="OSAGARY"></a>
			<!-- <%= link_to("OSAGARI", "/") %> -->
        </div>
    </header>
    <main class="container">
  		<div class="contents"><!-- ここまで定型 -->
            <div class="cttHead"><!-- コンテンツの見出し -->
				<h2>ユーザー情報登録</h2>		  				
		  	</div>
            <div class="mainForm"><!-- フォーム作るときはこれ　tagはdivがよさげ -->
                <%= form_tag("/signup4",{:multipart => true}) do %>
                    <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
                        <label>ニックネーム</label>
                        <strong>必須</strong><!-- 必須マーク -->
                        <%# <input class="form-element form-field" name="username" type="email" id="#" required="required"><!-- form内の要素にはform-elementをつける fieldの場合form-fieldをつける --> %>
                        <%= text_field_tag("name",@user.name, :class =>'form-element form-field')%>
                    </div>

                    <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
                        <label>所属課程・専攻</label>
                        <strong>必須</strong><!-- 必須マーク -->
                        <%# <input class="form-element form-field" name="username" type="email" id="#" required="required"><!-- form内の要素にはform-elementをつける fieldの場合form-fieldをつける --> %>
                        <%= select_tag("course_id",
                        options_for_select(@select_course,:selected => @user.course_id),
                        {class: "form-element"})%>
                    </div>

                    <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
                        <label>サークル・部活動</label>
                        <strong>必須</strong><!-- 必須マーク -->
                        <%= text_field_tag("club",@user.club, :class =>'form-element form-field')%>
                    </div>

                    <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
                        <label>学年</label>
                        <strong>必須</strong><!-- 必須マーク -->
                        <%= select_tag("entry_year",
                        options_for_select(@select_entry_year,:selected => @user.entry_year),
                        {class: "form-element"})%>
                    </div>

                    <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
                        <label>性別</label>
                        <strong>必須</strong><!-- 必須マーク -->
                        <%= select_tag("gender",
                        options_for_select(User.genders.map { |key, value| [I18n.t("enums.user.gender.#{key}"), value] }, :selected => User.genders[@user.gender]),
                        {class: "form-element"})%>
                    </div>

                    <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
                        <label>アイコン</label>
                        <%= file_field_tag( 'icon', :class =>'form-element') %>
                    </div>

         <%= submit_tag("確認画面へ", :class =>'form-element button button-Primary') %>
<% end %>
            </div>
        </div>
    </main>
<footer class="pageFoot">
    <div class="footer-bottom">
        <div class="kigyologo">
            <a href="/top"><img src="#" alt="OSAGARI"></a>
        </div>
        <div class="copyright">
            <small>&copy; <span>2019</span>京都学生起業部</small>
        </div>
    </div>
</footer>
</div>

app/views/users/signup4.html.erb
<div class="wrapper">
	<header class="slimHead"><!-- ボタン無しヘッダー -->
        <div class="logo">
			<a href="#"><img src="#" alt="OSAGARY"></a>
			<!-- <%= link_to("OSAGARI", "/") %> -->
        </div>
  </header>
  <main class="container">
  	<div class="contents"><!-- ここまで定型 -->
      <div class="cttHead"><!-- コンテンツの見出し -->
			  <h2>登録情報確認</h2>
	    </div>
      <div class="mainForm"><!-- フォーム作るときはこれ　tagはdivがよさげ -->
        <%= form_tag("/users/create",{:multipart => true}) do %>
          <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
            <label>ニックネーム</label>
            <%= @user.name%>
            <%= hidden_field_tag "name", @user.name %>
          </div>

          <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
            <label>所属課程・専攻</label>
            <%= @course_name %>
            <%= hidden_field_tag "course_id", @user.course_id, :class =>'form-element' %>
          </div>

          <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
            <label>サークル・部活動</label>
              <% if @user.club.present? then %>
                <%= @user.club %>
                <%= hidden_field_tag "club", @user.club, :class =>'form-element' %>
              <% else %>
                <p>選択されていません</p>
              <% end %>
          </div>

          <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
                    <label>学年</label>
                    <%= @user_great %>
                    <%= hidden_field_tag "entry_year", @user.entry_year, :class =>'form-element' %>
          </div>

          <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
                    <label>性別</label>
                    <%= @user.gender_i18n %>
                    <%= hidden_field_tag "gender", User.genders[@user.gender], :class =>'form-element' %>
          </div>

          <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
                    <label>アイコン</label>
                    <% if @user.icon.url then %>
                      <%= image_tag @user.icon.url %>
                      <%= hidden_field_tag :"cache[icon]", @user.icon.cache_name, :class =>'form-element' %>
                    <% end %>
          </div>

          <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
                    <%= submit_tag("修正する",name: 'back', :class =>'form-element button button-Alert') %>
          </div>

          <div class="form-element-wrapper"><!-- form内の要素の一塊にはform-element-wrapperをつける -->
                    <%= submit_tag("登録", :class =>'form-element button button-Primary') %>
          </div>
        <% end %>
      </div>
    </div>
  </main>
  <footer class="pageFoot">
    <div class="footer-bottom">
        <div class="kigyologo">
            <a href="/top"><img src="#" alt="OSAGARI"></a>
        </div>
        <div class="copyright">
            <small>&copy; <span>2019</span>京都学生起業部</small>
        </div>
    </div>
  </footer>
</div>