config/routes.rb
Rails.application.routes.draw do

  devise_for :accounts, :controllers =>{:registrations => 'accounts/registrations',:confirmations => 'accounts/confirmations'}
  post "likes/:post_id/create" => "likes#create"
  post "likes/:post_id/destroy" => "likes#destroy"



  get "admin/user" => "admin#user"
  post "admin/user" => "admin#user"
  post "admin/user/:user_id/ban" =>"admin#user_ban"
  post "admin/user/:user_id/suspend" =>"admin#user_suspend"
  get 'admin/post' => "admin#post"
  post 'admin/post' => "admin#post"
  get 'admin/transaction'

  post "users/:id/update"  => "users#update"
  get "users/edit"     => "users#edit"
  post "users/edit_confirm" => "users#edit_confirm"
  post "users/update"      => "users#update"
  post "users/create"      => "users#create"
  get "users/index"        => "users#index"
  get "users/show/:id"          => "users#show"
  post "login"             => "home#login"
  post "logout"            => "home#logout"
  get "login"              => "home#login"
  get "users/mail_confirm"       => "users#mail_confirm", as: 'users_mail_confirm'
  get "users/signup"             => "users#signup", as: 'users_signup'
  get "users/signup_confirm"     => "users#signup_confirm"
  post "users/signup_confirm"    => "users#signup_confirm"


  get "posts/search" => "posts#search"
  post "posts/search" => "posts#search"
  get "posts/index" => "posts#index"
  get "posts/new" => "posts#new"
  get "posts/show/:id" => "posts#show"
  post "posts/create" => "posts#create"
  post "posts/create_confirm" => "posts#create_confirm"
  get "posts/edit/:id" => "posts#edit"
  post "posts/edit_confirm/:id" => "posts#edit_confirm"
  post "posts/update/:id" => "posts#update"
  post "posts/destroy/:id" => "posts#destroy"
  get "posts/chat_confirm/:id" => "posts#chat_confirm"

  post "chats/:book_id/start"            => "chats#start"
  post "chats/:transaction_id/send_chat" => "chats#send_chat"
  get "chats/:transaction_id/chat"       => "chats#chat"
  post "chats/:transaction_id/cansel_exhibit"  => "chats#cansel_exhibit"
  post "chats/:transaction_id/cansel_parchase" => "chats#cansel_parchase"
  get "chats/:transaction_id/buy_complete_comfirm"        => "chats#buy_complete_comfirm"
  post "chats/:transaction_id/buy_complete_comfirm_done"  => "chats#buy_complete_comfirm_done"
  get "chats/:transaction_id/sale_complete_comfirm"       => "chats#sale_complete_comfirm"
  post "chats/:transaction_id/sale_complete_comfirm_done" => "chats#sale_complete_comfirm_done"




  root 'home#top'
  get 'home/top' => 'home#top'
  get "/about" => 'home#about'
  get "/policy" => 'home#policy'
  get "/privacy" => 'home#privacy'
  get "/help" => 'home#help'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'index/index'
  # post "index/index"
  #
  # get 'index', to: 'index#index'
  # get 'index/chatani'
end

app/views/layouts/_footer.html.erb
<footer class="pageFoot">
    <div class="footer-upper">
        <nav>
            <ul>
			    <li class="footer-cell">
    				<h2>OSAGARYについて</h2>
					<ul>
                        <li>
                            <%= link_to("OSAGARYとは", "/about" ) %>
                        </li>
                        <li>
                            <%= link_to("ヘルプ", "/help") %>
                        </li>
                        <li>
                            <%=link_to("利用規約","/policy")%>
                        </li>
                        <li>
                            <%=link_to("プライバシーポリシー","/privacy")%>
                        </li>
					</ul>
				</li>
			  	<li class="footer-cell">
					<h2>運営団体「京都学生起業部」について</h2>
					<ul>
						<li>
							<%=link_to("公式ホームページ","https://www.kit-kigyobu.com/")%>
                    	</li>
						<li>
                            <%=link_to("公式Twitter","https://twitter.com/kigyo_bu")%>
						</li>
						<li>
                            <%=link_to("公式ブログ","https://kigyobuproject.hatenablog.com/")%>
						</li>
					</ul>
            	</li>
			</ul>        
        </nav>
    </div>  

    <div class="footer-bottom">
        <div class="kigyologo">
            <%= link_to image_tag("/assets/logo_mt_w.png", :class=>"logo logo_mono"), "/" %>
        </div>
        <div class="copyright">
            <small>&copy; <span>2019</span>京都学生起業部</small>
        </div>
    </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<html>
  <head>
    <title>OSAGARY</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 
  <script>
    (function(d) {
      var config = {
        kitId: 'akr2tcz',
        scriptTimeout: 3000,
        async: true
      },
      h=d.documentElement,t=setTimeout(function(){h.className=h.className.replace(/\bwf-loading\b/g,"")+" wf-inactive";},config.scriptTimeout),tk=d.createElement("script"),f=false,s=d.getElementsByTagName("script")[0],a;h.className+=" wf-loading";tk.src='https://use.typekit.net/'+config.kitId+'.js';tk.async=true;tk.onload=tk.onreadystatechange=function(){a=this.readyState;if(f||a&&a!="complete"&&a!="loaded")return;f=true;clearTimeout(t);try{Typekit.load(config)}catch(e){}};s.parentNode.insertBefore(tk,s)
    })(document);
  </script>

 </head>

  <header>
    <nav class="navbar navbar-expand-lg navbar-default nav-bg">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to image_tag("/assets/logo_mtr_c.png", :class=>"navbar-brand z-999"), "/" %>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbarSupportedContent" aria-expanded="true">
          <ul class="navbar-left nav navbar-nav my-xs-invisible">
            <li>
              <%=form_tag("/posts/search", :class=>"navbar-form inline-form z-999") do%>
                <input name="search_word" class="form-control" type="search" placeholder="検索..." aria-label="Search">
              <% end %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">

            <% if @current_user %>
            <!-- ログイン後、ユーザ登録がされているとき -->
              <li>
                <%=link_to("#{@current_user.name}","/users/show/#{@current_user.id}")%>
              </li>
              <li>
                <%=link_to("出品","/posts/new")%>
              </li>
              <li>
                <%= link_to("ログアウト", destroy_account_session_path, {method: :delete}) %>
              </li>
            <% elsif @current_account_id %>
            <!-- ログイン後、ユーザ登録がされていないとき -->
              <li>
                <%= link_to("プロフィール設定", "/users/signup") %>
              </li>
              <li>
                <%= link_to("ログアウト", destroy_account_session_path, {method: :delete}) %>
              </li>
            <% else %>
            <!-- ログインされていない時 -->
              <li>
                <%= link_to("ログイン", "/login") %>
              </li>
              <li>
                <%= link_to("新規登録", "/accounts/sign_up") %>
              </li>
            <% end %>

          </ul>
        </div>

          <%=form_tag("/posts/search", :class=>"navbar-form inline-form my-xs-visible") do%>
            <input name="search_word" class="form-control" type="search" placeholder="検索..." aria-label="Search">
          <% end %>
      </div>
    </nav>
  </header>

  <% if flash[:notice] %>
    <div class="flash alert alert-success alert-dismissible fade in">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <body>

    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>